config/routes.rb
Doubleoptin::Engine.routes.draw do
  get :subscription, to: 'subscribers#new'
  post :subscribe, to: 'subscribers#create'
  get :confirm, to: 'subscribers#confirm'
  get :unsubscribe, to: 'subscribers#unsubscribe'

  scope :admin do
    resources :subscribers, except: [:new, :create]
  end
  root to: 'subscribers#new'
end

app/models/doubleoptin/application_record.rb
module Doubleoptin
  class ApplicationRecord < ActiveRecord::Base
    self.abstract_class = true
  end
end

app/models/doubleoptin/subscriber.rb
module Doubleoptin
  class Subscriber < ApplicationRecord
    before_validation :normalize_email, on: :create
    validates :email, format: { with: URI::MailTo::EMAIL_REGEXP }
    validates :email, presence: true, on: :create
    validates :email, uniqueness: true, on: :create, if: :all_previous_gone?
    validates :name, presence: true, on: :create

    def normalize_email
      email.downcase!
    end

    def all_previous_gone?
      ! self.class.where(email: email).not_gone.empty?
    end

    def active?
      confirmed and not unsubscribed or false
    end

    scope :not_gone, -> { where(unsubscribed: [nil, false]) }
    scope :active, -> { not_gone.where(confirmed: true) }

    def address
      "#{name} <#{email}>"
    end

    def confirm_link
      @confirm ||= digest :confirm
    end

    def unsubscribe_link
      @unsubscribe ||= digest :unsubscribe
    end

    private

    def digest(nonce)
      self.class.digest(nonce, email)
    end

    class << self
      # Return the last subscriber with the email
      def find_by_nonce(nonce, digest)
        found = all.map(&:email).find do |email|
          digest(nonce, email) == digest
        end
        self.where(email: found).last
      end

      # Return a hash digest made of three parts:
      # - a given nonce
      # - a given email adddress
      # - the number of times that the email address appears in the DB
      def digest(nonce, email)
        Digest::MD5.hexdigest("#{nonce}:#{where(email: email).size}:#{email}")
      end
    end
  end
end

app/controllers/doubleoptin/application_controller.rb
module Doubleoptin
  class ApplicationController < ::ApplicationController
    protect_from_forgery with: :exception
  end
end

app/controllers/doubleoptin/subscribers_controller.rb
require_dependency "doubleoptin/application_controller"

module Doubleoptin
  class SubscribersController < ApplicationController
    before_action :authenticate, only: [:index, :edit, :update, :destroy]
    before_action :set_subscriber, only: [:edit, :update, :destroy]

    def new
      @subscriber = Doubleoptin::Subscriber.new
    end

    def create
      @subscriber = Doubleoptin::Subscriber.new params.require(:subscriber).permit(:name, :email)

      respond_to do |format|
        if @subscriber.save
          SubscriptionMailer.confirm(@subscriber).deliver_now
          format.html
        else
          format.html { redirect_to subscription_path }
        end
      end
    end

    # POST /confirm?key=1 (not REST)
    def confirm
      @subscriber = Doubleoptin::Subscriber.find_by_nonce :confirm, params[:key]

      respond_to do |format|
        if !@subscriber.unsubscribed && @subscriber.try(:update_attribute, :confirmed, true)
          format.html
        else
          format.html { redirect_to :root }
        end
      end
    end

    # POST /unsubscribe?key=1 (not REST)
    def unsubscribe
      @subscriber = Doubleoptin::Subscriber.find_by_nonce :unsubscribe, params[:key]

      respond_to do |format|
        if @subscriber.try :update_attribute, :unsubscribed, true
          format.html
        else
          format.html { redirect_to :root }
        end
      end
    end

    def index
      @subscribers = Subscriber.all
    end

    def edit
    end

    def update
      respond_to do |format|
        if @subscriber.update params.require(:subscriber).permit(:name, :email, :unsubscribed, :confirmed)
          format.html { redirect_to subscribers_url, notice: 'Subscriber was successfully updated.' }
          format.json { render :index, status: :ok }
        else
          format.html { render :edit }
          format.json { render json: @subscriber.errors, status: :unprocessable_entity }
        end
      end
    end

    def destroy
      @subscriber.destroy
      respond_to do |format|
        format.html { redirect_to subscribers_url, notice: 'Subscriber was successfully destroyed.' }
        format.json { head :no_content }
      end
    end

    def authenticate
      super
    end

    private

    def set_subscriber
      @subscriber = Subscriber.find(params[:id])
    end

  end
end

app/helpers/doubleoptin/application_helper.rb
module Doubleoptin
  module ApplicationHelper
  end
end

app/helpers/doubleoptin/subscribers_helper.rb
module Doubleoptin
  module SubscribersHelper
  end
end

app/views/doubleoptin/subscribers/_form.html.erb
<%= form_with(model: subscriber, local: true) do |form| %>
  <% if subscriber.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(subscriber.errors.count, "error") %> prohibited this subscriber from being saved:</h2>

      <ul>
      <% subscriber.errors.full_messages.each do |message| %>
        <li><%= message %></li>
      <% end %>
      </ul>
    </div>
  <% end %>

  <div class="field">
    <%= form.label :name %>
    <%= form.text_field :name %>
  </div>

  <div class="field">
    <%= form.label :email %>
    <%= form.text_field :email %>
  </div>

  <div class="field">
    <%= form.label :confirmed %>
    <%= form.check_box :confirmed %>
  </div>

  <div class="field">
    <%= form.label :unsubscribed %>
    <%= form.check_box :unsubscribed %>
  </div>

  <div class="actions">
    <%= form.submit %>
  </div>
<% end %>

app/views/doubleoptin/subscribers/confirm.html.slim
h2 Welcome
p You have successfully confirmed your email address for this list.

app/views/doubleoptin/subscribers/create.html.slim
h2
  ' Thank you for your request,
  = @subscriber.name
p You will now receive an email at your given adddress. This ensures that it is really you who made the request.

app/views/doubleoptin/subscribers/edit.html.erb
<h1>Editing Subscriber</h1>

<%= render 'form', subscriber: @subscriber %>

<%= link_to 'Back', subscribers_path %>

app/views/doubleoptin/subscribers/index.html.erb
<p id="notice"><%= notice %></p>

<h1>Subscribers</h1>

<table>
  <thead>
    <tr>
      <th>Name</th>
      <th>Email</th>
      <th>Confirmed</th>
      <th>Unsubscribed</th>
      <th>Active</th>
      <th colspan="2"></th>
    </tr>
  </thead>

  <tbody>
    <% @subscribers.each do |subscriber| %>
      <tr>
        <td><%= subscriber.name %></td>
        <td><%= subscriber.email %></td>
        <td><%= subscriber.confirmed %></td>
        <td><%= subscriber.unsubscribed %></td>
        <td><%= subscriber.active? %></td>
        <td><%= link_to 'Edit', edit_subscriber_path(subscriber) %></td>
        <td><%= link_to 'Destroy', subscriber, method: :delete, data: { confirm: 'Are you sure?' } %></td>
      </tr>
    <% end %>
  </tbody>
</table>

<br>

<%= link_to 'New Subscriber', subscription_path %>

app/views/doubleoptin/subscribers/new.html.slim
= form_for @subscriber, url: :subscribe do |f|
  .field
    = f.label :name
    = f.text_field :name, required: true, placeholder: "Name"
  .field
    = f.label :email
    = f.text_field :email, required: true, placeholder: "Email"
  .field
    = f.submit 'Subscribe'

app/views/doubleoptin/subscribers/unsubscribe.html.slim
h2 Goodbye
p You have successfully unsubscribed your email address from this list.

app/views/layouts/doubleoptin/application.html.erb
<!DOCTYPE html>
<html>
<head>
  <title>Doubleoptin</title>
  <%= csrf_meta_tags %>
  <%= csp_meta_tag %>

  <%= stylesheet_link_tag    "doubleoptin/application", media: "all" %>
  <%= javascript_include_tag "doubleoptin/application" %>
</head>
<body>

<%= yield %>

</body>
</html>